### ISSUE TITLE
Support Enterprise Solid Server (ESS)

### ISSUE THREAD

**Issue by angelo-v** [codecentric/web-clip#21]
As the owner of a pod at inrupt pod spaces
I want to use my pod with WebClip
So that I do not have to create a pod elsewhere just to use WebClip

Background info:

Clipping to Inrupt Pod Spaces (which is based on ESS) failed:

```undefined Error: Update: Loaded <https://pod.inrupt.com/aveltens/webclip/2022/04/01/1ae56569-b2fb-44f1-9020-d81b8e0dcfd8>but stil can't figure out what editing protcol it supports. undefined at UpdateManager.update (chrome-extension://jjmieagjdpgikkkcnpagkbdldcalmola/background.js:65457:19) undefined at chrome-extension://jjmieagjdpgikkkcnpagkbdldcalmola/background.js:65466:22```

**Comment by angelo-v** [comment]
caused by https://github.com/linkeddata/rdflib.js/issues/473
